name: Publish to NPM

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@haloivanid'

      - name: Install semantic-release
        run: npm i -g semantic-release

      - name: Set up Yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build lib folder
        run: ./build.sh

      - name: Publish to NPM
        run: |
          cd lib
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
